-- liquibase formatted sql

-- changeset Homychok:1
CREATE TABLE student (
                         id  BIGSERIAL PRIMARY KEY,
                         student_age         INTEGER NOT NULL,
                         student_name        VARCHAR(255) NOT NULL,
                         faculty_id  BIGINT REFERENCES faculty(id)
);

-- ALTER TABLE student ALTER COLUMN student_id ADD GENERATED BY DEFAULT AS IDENTITY;